spring.application.name=storage-service


jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration-minutes=60

spring.datasource.url=jdbc:postgresql://localhost:5432/file_store_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Configuracion para AWS S3 // en este caso usamos MinIO para simular un servicio s3
storage.endpoint=http://localhost:9000
storage.region=us-east-1
storage.bucket=files
storage.access-key=admin
storage.secret-key=admin123456